[project]
name = 'contracts'
description = ''
authors = ['Matija OsreÄki']
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.hello-stacks]
path = 'contracts/hello-stacks.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
